{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(deleteRequests_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Delete Requests"
    },
    {
     "expr": "rate(getRequests_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Get Requests"
    },
    {
     "expr": "rate(postRequests_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Post Requests"
    },
    {
     "expr": "rate(putRequests_total{source=\"jwt-pizza-service-dev\"}[$__rate_interval])",
     "legendFormat": "Put Requests"
    },
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "memory_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(successfulAuth_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Successful Auth"
    },
    {
     "expr": "rate(failedAuth_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failed Auth"
    },
    {
     "expr": "rate(totalAuthAttemps_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Total Auth Attempts"
    }
   ]
  },
  {
   "title": "Pizzas Sold per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(totalPizzas_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizzas Sold"
    }
   ]
  },
  {
   "title": "Creation Failures per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(creationFailures_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Creation Failures"
    }
   ]
  },
  {
   "title": "Revenue per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "rate(totalRevenue_total[1m])", "legendFormat": "Revenue" }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(requestLatency_milliseconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(pizzaLatency_milliseconds_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Num Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "numUsers_total", "legendFormat": "NumUsers" }
   ]
  }
 ]
}